apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: microservices

data:
  MYSQL_HOST: host.minikube.internal 
  MYSQL_USER: root
  MYSQL_DB: user
  MYSQL_PORT: "3306" 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: microservices
data:
  rabbitmq_user: puppet
  rabbitmq_password: password
