apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: microservices

stringData:
  MYSQL_PASSWORD: password
  # jwt : book
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: microservices

stringData:
  RABBITMQ_DEFAULT_PASS: password
  # jwt : book
type: Opaque

---