apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices

spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001