route:
  receiver: 'slack'

receivers:
  - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'


# global:
#   resolve_timeout: 5m

# route:
#   receiver: 'slack-notifications'

# receivers:
#   - name: 'slack-notifications'
#     slack_configs:
#       - api_url: 'https://hooks.slack.com/services/your/slack/hook'
#         channel: '#alerts'
