# log:
#   level: INFO
#   format: common  # common, json, logfmt
#   filePath: /var/log/traefik/traefik.log

# api:
#   insecure: true
#   dashboard: true

# entryPoints:
#   web:
#     address: ":80"

# providers:
#   docker:
#     endpoint: "unix:///var/run/docker.sock"
#     exposedByDefault: false


api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

http:
  routers:
    auth:
      entryPoints: web
      rule: "Host(`auth.example.com`)"
      service: auth
      tls:
        certResolver: myresolver
    user:
      entryPoints: web
      rule: "Host(`user.example.com`)"
      service: user
      tls:
        certResolver: myresolver
    rabbitmq:
      entryPoints: web
      rule: "Host(`rabbitmq.example.com`)"
      service: rabbitmq
      tls:
        certResolver: myresolver
    prometheus:
      entryPoints: web
      rule: "Host(`prometheus.example.com`)"
      service: prometheus
      tls:
        certResolver: myresolver
    grafana:
      entryPoints: web
      rule: "Host(`grafana.example.com`)"
      service: grafana
      tls:
        certResolver: myresolver
    cadvisor:
      entryPoints: web
      rule: "Host(`cadvisor.example.com`)"
      service: cadvisor
      tls:
        certResolver: myresolver
    alertmanager:
      entryPoints: web
      rule: "Host(`alertmanager.example.com`)"
      service: alertmanager
      tls:
        certResolver: myresolver

services:
  auth:
    loadBalancer:
      servers:
        - url: "http://auth-service:8080"
  user:
    loadBalancer:
      servers:
        - url: "http://user-service:8081"
  rabbitmq:
    loadBalancer:
      servers:
        - url: "http://rabbitmq:15672"
  prometheus:
    loadBalancer:
      servers:
        - url: "http://prometheus:9090"
  grafana:
    loadBalancer:
      servers:
        - url: "http://grafana:3000"
  cadvisor:
    loadBalancer:
      servers:
        - url: "http://cadvisor:8080"
  alertmanager:
    loadBalancer:
      servers:
        - url: "http://alertmanager:9093"
