http:
  routers:
    auth-router:
      rule: "Host(`localhost`) && PathPrefix(`/login`)"
      service: "auth-service"
      middlewares:
        - "jwt-auth"

    user-service-router:
      rule: "Host(`localhost`) && PathPrefix(`/profile`)"
      service: "user-service"
      middlewares:
        - "jwt-auth"

    order-router:
      rule: "Host(`localhost`)"
      service: "order-service"

    payment-router:
      rule: "Host(`localhost`) && PathPrefix(`/checkout`)"
      service: "payment-service"
      middlewares:
        - "jwt-auth"

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:5001"

    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:5000"

    order-service:
      loadBalancer:
        servers:
          - url: "http://order-service:5003"

    payment-service:
      loadBalancer:
        servers:
          - url: "http://payment-service:5004"


middlewares:
  jwt-auth:
    jwt:
      issuer: "https://issuer.example.com"
      header: "Authorization"
      payload: "{\"iss\":\"https://auth.example.com\",\"exp\":3600}"

###
# Traefik configuration
# entryPoints:
#   web:
#     address: ":80"
#   websecure:
#     address: ":443"

# http:
#   routers:
#     service1-router:
#       rule: "Host(`service1.example.com`)"
#       service: "service1"
#       middlewares:
#         - "authMiddleware"
#       tls: {}
#     service2-router:
#       rule: "Host(`service2.example.com`)"
#       service: "service2"
#       middlewares:
#         - "authMiddleware"
#       tls: {}

#   middlewares:
#     authMiddleware:
#       rbac:
#         policies:
#           role1:
#             policy: "deny"
#             principals:
#               users: ["user1"]
#             resources:
#               services: ["service1"]
#               methods: ["GET"]
#           role2:
#             policy: "allow"
#             principals:
#               users: ["user2"]
#             resources:
#               services: ["service2"]
#               methods: ["GET"]