apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: microservices
type: Opaque
data:
  DATABASE_USERNAME: cm9vdA==
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # echo -n 'my_db_user' | base64
