apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservices
type: Opaque
data:
  DATABASE_USER: cm9vdA==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # echo -n 'my_db_user' | base64
