database:
  user: root    
  password: password
  host: localhost
  port: 3306
  database: mysql_app

http_server:
  HTTP_PORT: 5000

rabbitmq:
  host: rabbitmq
  user: guest
  password: guest
  port: 5672
  #url: amqp://guest:guest@rabbitmq:5672/

constants:
  maxItemsPerPage: 20
  maxRetryAttempts: 3

statics:
  welcomeMessage: "Welcome to our user service!"
  defaultUserRole: "user"

logger:
  FileName: "./data/logs/log.json"
  Localtime: false
  MazSize: 50
  MaxBackups: 3
  MaxAge: 28
  Compass: true