apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: microservices
data:
  #PLACEHOLDER: "NONE"
  MYSQL_HOST: host.minikube.internal
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: mysql_app
  
