apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: microservices
type: Opaque
data:
  MYSQL_USERNAME: cm9vdA==
  MYSQL_PASSWORD: cGFzc3dvcmQ= 
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= 
   # echo -n 'my_db_user' | base64
