apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
