apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: microservices
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cHVwcGV0 # echo -n 'rabbit_user' | base64
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=