apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices
type: Opaque
data:
  RABBITMQ_USERNAME: cHVwcGV0 # echo -n 'rabbit_user' | base64
  RABBITMQ_PASSWORD: cGFzc3dvcmQ=