apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
  storageClassName: local-storage # Replace with your storage class (e.g., local-storage)
