apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices
type: Opaque
data:
  username: cHVwcGV0 # echo -n 'rabbit_user' | base64
  password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: microservices
type: Opaque
data:
  POSTGRES_USER: cm9vdA==  # echo -n 'my_db_user' | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # echo -n 'my_password123' | base64
